# Generated by Django 5.0.4 on 2024-05-08 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expence_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expence',
            old_name='name',
            new_name='expence_name',
        ),
    ]
